version: 2

formats: []

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

